name: Upload AWS Device Farm Apple iOS test specs

on:
  pull_request:
    paths:
      - .github/workflows/upload-apple-test-specs.yml
      - extension/benchmark/apple/Benchmark/default-ios-device-farm-appium-test-spec.yml.j2
  push:
    branches:
      - main
    paths:
      - .github/workflows/upload-apple-test-specs.yml
      - extension/benchmark/apple/Benchmark/default-ios-device-farm-appium-test-spec.yml.j2

concurrency:
  # NB: This concurency group needs to be different than the one used in apple-perf, otherwise
  # GH complains about concurrency deadlock
  group: apple-spec-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

jobs:
  validate-apple-test-spec:
    uses: ./.github/workflows/apple-perf.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      # Just use a small model here with a minimal amount of configuration to test the spec
      models: stories110M
      devices: apple_iphone_15
      delegates: xnnpack
